import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { getApp } from "firebase/app";
import { collection, getDocs, getFirestore } from "firebase/firestore";

const Home: NextPage = () => {
  const fetchData = async () => {
    const db = getFirestore(getApp());
    const col = collection(db, "data");
    const data = (await getDocs(col)).docs.map((doc) => doc.data());
    console.log(data);
  };

  return (
    <div>
      <Head>
        <title>ARCi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Welcome to ARCi</div>
      <Button variant="contained" onClick={fetchData}>
        Fetch Data
      </Button>
    </div>
  );
};

export default Home;
