import { Box, Button, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import BorderColorOutlinedIcon from "@mui/icons-material/BorderColorOutlined";
import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
import PeopleAltOutlinedIcon from "@mui/icons-material/PeopleAltOutlined";
import { Icon } from "@mui/material";

const Login = () => {
  const loginOptions = [
    { name: "Admin", icon: BorderColorOutlinedIcon },
    { name: "Inspector", icon: VisibilityOutlinedIcon },
    { name: "Lab Member", icon: PeopleAltOutlinedIcon },
  ];

  return (
    <>
      <Head>
        <title>ARCi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          width: "100vw",
          height: "100vh",
          background:
            "linear-gradient(rgba(103,129,222,1), rgba(177,190,239,1))",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            flex: "1",
            gap: "0.25rem",
          }}
        >
          <Image
            src="/logo.png"
            width="48px"
            height="48px"
            alt="Logo"
            color="white"
          />
          <Typography color="white" variant="h4">
            ARCi
          </Typography>
        </Box>
        <Box sx={{ flex: "5", display: "flex", margin: "2rem" }}>
          <Box sx={{ margin: "auto" }}>
            <Box
              sx={{
                backgroundColor: "#F0F0F0",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: "2rem",
                padding: "2rem 4rem 3rem",
                width: { xs: "100%", md: "685px" },
                borderRadius: "14px",
              }}
            >
              <Typography variant="h5" color="appBlack">
                I am...
              </Typography>
              <Box
                sx={{
                  display: "flex",
                  flexDirection: "column",
                  width: { xs: "100%", sm: "400px", md: "450px" },
                  gap: "1.5rem",
                }}
              >
                {loginOptions.map((option) => (
                  <Button
                    variant="contained"
                    key={option.name}
                    color={"appGrey"}
                    size="large"
                  >
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "center",
                        gap: "1rem",
                      }}
                    >
                      <Icon component={option.icon} />
                      <Typography variant="h6">{option.name}</Typography>
                    </Box>
                  </Button>
                ))}
              </Box>
            </Box>
          </Box>
        </Box>
        <Box sx={{ flex: "1" }} />
      </Box>
    </>
  );
};

export default Login;
